name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test HTML
      id: test-html
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test HTML
        setup-command: pip install webcode-tk file-clerk
        command: pytest tests/test_html.py
        timeout: 10
        max-score: 3
    - name: Test CSS
      id: test-css
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test CSS
        setup-command: pip install webcode-tk file-clerk
        command: pytest tests/test_css.py
        timeout: 10
        max-score: 3
    - name: Test Exceeds
      id: test-exceeds
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Exceeds
        setup-command: pip install webcode-tk file-clerk
        command: pytest tests/test_exceeds.py
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-HTML_RESULTS: "${{steps.test-html.outputs.result}}"
        TEST-CSS_RESULTS: "${{steps.test-css.outputs.result}}"
        TEST-EXCEEDS_RESULTS: "${{steps.test-exceeds.outputs.result}}"
      with:
        runners: test-html,test-css,test-exceeds
